### ISSUE TITLE
При установке ServiceProvider теряется

### ISSUE THREAD

**Issue by altpoint** [greabock/console#1]
После установки
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Greabock\Console\ServiceProvider' not found

Хот, он таки прописан в config.

PHP Fatal error:  Class 'Greabock\Console\ServiceProvider' not found in app_root/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

И composer dump-autoload выполнял и всё как обычно делал, никакого эффекту. Что может быть не так?

**Comment by greabock** [comment]
гляну вечерком, вроде проверял, вроде работало )

**Comment by greabock** [comment]
Пропустил запись автозагрузки, в файле composer.json. Исправлено

**Comment by greabock** [comment]
https://github.com/greabock/console/commit/5ea7b51ded2559a40d47ac260b69c469011d183f

**Comment by altpoint** [comment]
отдуши внатуре, а то мне этой консоли прям не хватает при разработке, на 4 ларке привык к ней.

**Comment by greabock** [comment]
@altpoint :+1:

**Comment by altpoint** [comment]
Кстати, по ходу вот почему нет консоли https://www.youtube.com/watch?v=-IYhS7QRNjI
Потому что она в консоли )

**Comment by greabock** [comment]
@altpoint дык тинкер еще с бородатой 4.0 версии доступен (а может и раньше). Вопрос был в доступе из браузера. Ну как бы вот.
